name: lookt
description: Find your items!
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.8.3
  provider: ^6.1.2
  go_router: ^13.2.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  google_fonts: ^6.2.0
  image_picker: ^1.1.0
  image: ^4.1.7
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.5
  connectivity_plus: ^6.0.3
  firebase_performance: ^0.9.4+5

dev_dependencies:
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  drift_dev: ^2.14.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_launcher.png

fonts:
  - family: Koulen
    fonts:
      - asset: assets/fonts/Koulen-Regular.ttf
  