// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBscAed5gbkjdoLSAHQuy23Se8dKmh5c',
    appId: '1:597801997046:web:367328a855fa62e85b52d7',
    messagingSenderId: '597801997046',
    projectId: 'centurion-3ca0c',
    authDomain: 'centurion-3ca0c.firebaseapp.com',
    storageBucket: 'centurion-3ca0c.appspot.com',
    measurementId: 'G-HZ9GQ3YLRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDI46NSJvwSyFrlHrnl7l1GrcJYpt5fk',
    appId: '1:597801997046:android:767108393eb9bd5e5b52d7',
    messagingSenderId: '597801997046',
    projectId: 'centurion-3ca0c',
    storageBucket: 'centurion-3ca0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_MQZkWFe2wORIqvG9e9i0UsvJTn5rao4',
    appId: '1:597801997046:ios:f38eb6669ec24bf35b52d7',
    messagingSenderId: '597801997046',
    projectId: 'centurion-3ca0c',
    storageBucket: 'centurion-3ca0c.appspot.com',
    iosBundleId: 'com.lookt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_MQZkWFe2wORIqvG9e9i0UsvJTn5rao4',
    appId: '1:597801997046:ios:f38eb6669ec24bf35b52d7',
    messagingSenderId: '597801997046',
    projectId: 'centurion-3ca0c',
    storageBucket: 'centurion-3ca0c.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUBscAed5gbkjdoLSAHQuy23Se8dKmh5c',
    appId: '1:597801997046:web:525ee73d720939715b52d7',
    messagingSenderId: '597801997046',
    projectId: 'centurion-3ca0c',
    authDomain: 'centurion-3ca0c.firebaseapp.com',
    storageBucket: 'centurion-3ca0c.appspot.com',
    measurementId: 'G-NTBXGY3WJC',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBUBscAed5gbkjdoLSAHQuy23Se8dKmh5c',
    appId: '1:597801997046:web:3331d69b64e7e5cb5b52d7',
    messagingSenderId: '597801997046',
    projectId: 'centurion-3ca0c',
    authDomain: 'centurion-3ca0c.firebaseapp.com',
    storageBucket: 'centurion-3ca0c.appspot.com',
    measurementId: 'G-56D7GC7QDF',
  );
}